<?php
require(APP_PATH . "config.php");

$link = mysql_connect($AppConfig['db']['host'], $AppConfig['db']['user'], $AppConfig['db']['password']) or die(mysql_error());
mysql_select_db($AppConfig['db']['database'], $link) or die(mysql_error());

$Id = $this->player->playerId;
$result = mysql_query("SELECT club FROM p_players WHERE id='" . $Id . "'");
while ($row = mysql_fetch_array($result)) {
    $club = $row['club'];
}

if ($club == '0') {
    echo '<h1>لم تفعل نادي الذهب</h1>
<p></p>
<p>لم تفعل نادي الذهب لكي تستمتع بهذه الميزة يجب تفعيل نادي الذهب نادي الذهب يكلف 100 ذهبه فقط لتفعيله 
<a href="plus.php?t=2#club">أضغط هنا</a> .</p>
<p></p>';
} else {
    if (isset($_GET['add'])) {
        ?>
        <form method="POST" action="">
            <h4 class="round">اضافة مزرعة جديدة</h4>
            <?php
            switch ($this->data['tribe_id']) {
                case 1:
                    $farmTroops = array(1, 2, 3, 5, 6);
                    break;
                case 2:
                    $farmTroops = array(11, 12, 13, 15, 16);
                    break;
                case 3:
                    $farmTroops = array(21, 22, 24, 25, 26);
                    break;
                case 6:
                    $farmTroops = array(51, 52, 53, 55, 56);
                    break;
                case 7:
                    $farmTroops = array(100, 101, 102, 104, 105);
                    break;
            }

            if (isset($_GET['id']) && is_numeric($_GET['id'])) {
                $vid = intval($_GET['id']);
                echo '<b class="error">.اختر عدد القوات ونوعها واضغط اضافة المزرعه</b>';
                if ($vid < 1) {
                    $vid = 1;
                }
                echo '<input type="hidden" name="vid" value="' . $vid . '">';
            }
            ?>
            <table id="plusFunctions" cellpadding="1" cellspacing="1">
                <thead>
                    <tr>
                        <th colspan="4"><center>اضافة مزرعه</center></th>
                    </tr>
                </thead>
                <tr>
                    <td><center>x</center></td>
                    <td><center><input type="text" maxlength="4" value="<?php echo isset($_POST['x']) && is_numeric($_POST['x']) ? $_POST['x'] : ''; ?>" name="x" class="text"></center></td>
                    <td><center>y</center></td>
                    <td><center><input type="text" maxlength="4" value="<?php echo isset($_POST['y']) && is_numeric($_POST['y']) ? $_POST['y'] : ''; ?>" name="y" class="text"></center></td>
                </tr>
                <tr>
                    <td><center>عدد القوات</center></td>
                    <td><center>
                        <select name="tid">
                            <?php
                            foreach ($farmTroops as $tid) {
                                foreach ($this->troops as $troopId => $troopNum) {
                                    if ($tid == $troopId) {
                                        $num = $troopNum;
                                    }
                                }
                                $troopName = htmlspecialchars(constant('troop_' . $tid));
                                ?>
                                <option value="<?php echo $tid; ?>"><?php echo $troopName; ?></option>
                                <?php
                            }
                            ?>
                        </select>
                        <input type="text" maxlength="6" value="2" name="tnum" class="text" size="5"></center>
                    </td>
                    <td colspan="2"><center><button class="text" name="add" type="submit" value="اضافة مزرعة" id="btn_ok"><div class="button-container"><div class="button-position"><div class="btl"><div class="btr"><div class="btc"></div></div></div><div class="bml"><div class="bmr"><div class="bmc"></div></div></div><div class="bbl"><div class="bbr"><div class="bbc"></div></div></div></div><div class="button-contents">اضافة مزرعة</div></div></button></center></td>
                </tr>
            </table>
        </form>
        <div class="clear"></div>
        <br>
        <?php if ($this->error != '') { ?><b class="error"><?php echo $this->error; ?></b> <?php } ?>
        <div class="clear"></div>
        <br>
        <br>
        <a href="farm.php" style="float:left;">العودة الى قائمة المزارع</a>
        <?php
    } else {
        ?>
        <form name="farm">
            <h2 class="round">قائمة المزارع</h2><br>
            قائمة المزارع يمكنك من خلالها اضافة اكبر عدد ممكن من المزارع والهجوم عليهم بضغطة زر أبدأ الان بتجميع مزارعك والهجوم عليها خلال ثانية بضغطه زر واحده .

            <script src="assets/jquery.js" type="text/javascript"></script>
            <script type="text/javascript">
                var tid = null;
                var i = null;
                var ii = null;

                function CheckAll(checked) {
                    var e = document.farm.elements.length;
                    var cnt = 0;
                    for (cnt = 0; cnt < e; cnt++) {
                        if (document.farm.elements[cnt].name == "list[]") {
                            document.farm.elements[cnt].checked = checked;
                        }
                    }
                }

                function farming() {
                    document.getElementById('farming').innerHTML = '<font color="#FF6F0F"><br>الرجاء الانتظار بينما يتم الهجوم</font><div class="clear"></div><br><div style="width: 0%; height: 10px; background-color: rgb(255, 0, 0);" id="loading"></div>';
                    i = 1;
                    tid = setTimeout(farming1, 1);
                }

                function farming1() {
                    var e = document.farm.elements.length;
                    var cnt = 0;
                    var not = true;
                    var farmingdata = null;
                    ii = 0;
                    for (cnt = 0; cnt < e; cnt++) {
                        if (document.farm.elements[cnt].name == "list[]") {
                            if (document.farm.elements[cnt].checked) {
                                ii += 1;
                            }
                        }
                    }
                    farming2();
                }

                function farming2() {
                    var troop = null;
                    var e = document.farm.elements.length;
                    var cnt = 0;
                    var not = true;
                    var farmingdata = null;
                    for (cnt = 0; cnt < e; cnt++) {
                        if (document.farm.elements[cnt].name == "list[]") {
                            if (document.farm.elements[cnt].checked) {
                                not = false;
                                document.farm.elements[cnt].checked = false;
                                document.getElementById('loading').style.width = ((i / ii) * 100) + '%';
                                farmingdata = document.farm.elements[cnt].value.split("|");

                                post_to_url("v2v.php", {
                                    'id': farmingdata[0],
                                    'c': '4',
                                    't[' + farmingdata[1] + ']': farmingdata[2],
                                    'farm': '1'
                                });

                                i += 1;
                                tid = setTimeout(farming2, 500);
                                break;
                            }
                        }
                    }
                    if (not == true) {
                        farming3();
                    }
                }

                function farming3() {
                    clearTimeout(tid);
                }

                function post_to_url(path, params) {
                    $.post(path, params).complete(function () {
                        // Optional callback
                    });
                }
            </script>
            <div id="farming"></div>
            <center>
                <input type="button" class="text" value="هجوم على المزارع" onclick="farming(); return false;">
                <input type="button" class="text" value="تحديد الكل" onclick="CheckAll(true); return false;">
                <input type="button" class="text" value="إلغاء الكل" onclick="CheckAll(false); return false;">
            </center>
        </form>
        <?php
        $result = mysql_query("SELECT * FROM p_farms WHERE player_id='" . $Id . "'");
        while ($row = mysql_fetch_array($result)) {
            echo '<div class="li"><input type="checkbox" name="list[]" value="' . $row['id'] . '|' . $row['type'] . '|' . $row['number'] . '"> <a href="village.php?id=' . $row['id'] . '">' . $row['id'] . '</a> ' . constant('troop_' . $row['type']) . ' (' . $row['number'] . ')</div>';
        }
    }
}
?>
