<?php


echo "<h1><p>";
echo '<b>قائمة<font color="#71D000"> p</font><font color="#FF6F0F">l</font>u<font color="#71D000">s</font></b>';
echo "</p></h1>\r\n<div id=\"textmenu\">\r\n   <a href=\"plus.php\"";
  if ($this->selectedTabIndex == 0) {
      echo " class=\"selected\"";
  }
  echo ">";
  echo LANGUI_PLUS_T3;
  echo "</a>\r\n | <a href=\"plus.php?t=2\"";
  if ($this->selectedTabIndex == 2) {
      echo " class=\"selected\"";
  }
  echo ">";
  echo LANGUI_PLUS_T5;
  echo "</a>\r\n | <a href=\"plus.php?t=4\"";
  if ($this->selectedTabIndex == 4) {
      echo " class=\"selected\"";
  }
  echo ">";
  echo "تحويل الذهب";
  echo "</a></div>\r\n";
  
  if ($this->selectedTabIndex == 0) {

      if ($this->packageIndex < 0) {
          echo "<div id=\"products\">\r\n\t";  
          $_c = 0;
          foreach ($this->appConfig['plus']['packages'] as $package) {
              ++$_c;
              echo "\t<table class=\"product lang_rtl lang_ar\" cellpadding=\"1\" cellspacing=\"1\">\r\n\t\t<thead>\r\n\t\t\t<tr><th>";
              echo $package['name'];
              echo "</th></tr>\r\n\t\t</thead>\r\n        <tbody>\r\n\t\t\t<tr><td class=\"pic\"><a target='_blank' href=\"";
              echo $package['link'] . "?client_reference_id=" . $this->player->playerId;
              echo "\"><img src=\"assets/default/plus/";
              echo htmlspecialchars($package['image']);
              echo "\" style=\"width:100px;height:100px;\" alt=\"";
              echo htmlspecialchars($package['name']);
              echo "\"></a></td></tr>\r\n            <tr><td>";
              echo $package['gold'];
              echo "&nbsp;";
              echo LANGUI_PLUS_T6;
              echo "</td></tr>\r\n            <tr><td>";
              echo $package['cost'];
              echo "&nbsp;";
              echo $package['currency'];
              echo "</td></tr>\r\n\t\t\t<tr><td><a target='_blank' class='signUpButton' href=\"";
              echo $package['link'] . "?client_reference_id=" . $this->player->playerId;
              echo "\">";
              echo LANGUI_PLUS_T7;
              echo "</a></td></tr>\r\n\t\t</tbody>\r\n\t</table>\r\n\t";
          }
          echo "\t<div class=\"clear\"></div>\r\n</div>\r\n";
      } else {
          $_c = 0;
          foreach ($this->appConfig['plus']['payments'] as $paymentKey => $payment) {
              ++$_c;
              echo "<table class=\"rate_details lang_rtl lang_ar\" cellpadding=\"1\" cellspacing=\"1\">\r\n    <thead>\r\n        <tr><th colspan=\"2\">";
              echo $_c . ". " . $payment['name'];
              echo "</th></tr>\r\n    </thead>\r\n    <tbody>\r\n        <tr>\r\n            <td class=\"pic\">\r\n\t\t\t\t<img src=\"assets/default/plus/";
              echo htmlspecialchars($this->appConfig['plus']['packages'][$this->packageIndex]['image']);
              echo "\" style=\"width:100px;height:100px;\" alt=\"";
              echo htmlspecialchars($this->appConfig['plus']['packages'][$this->packageIndex]['name']);
              echo "\">\r\n                <div>";
              echo text_period_lang;
              echo ": ";
              echo constant("payments_" . $paymentKey . "_period");
              echo "</div>\r\n            </td>\r\n            <td class=\"desc\">\r\n                ";
              echo constant("payments_" . $paymentKey . "_description");
              echo "<p>\r\n                <a href=\"#\" onclick=\"window. open('payment.php?p=";
              echo $paymentKey;
              echo "&pg=";
              echo $this->packageIndex;
              echo "','tgpay','scrollbars=yes,status=yes,resizable=yes,toolbar=yes,width=800,height=600');return false;\">\r\n                <img src=\"assets/default/plus/";
              echo htmlspecialchars($payment['image']);
              echo "\" style=\"width:119px; height:58px;\" alt=\"";
              echo htmlspecialchars($payment['name']);
              echo "\"></a>";
              echo "</tr>\r\n    </tbody>\r\n</table>\r\n";
          }
      }
  } else if ($this->selectedTabIndex == 2) {
      echo "<p>";
      if (0 < $this->data['gold_num']) {
          echo LANGUI_PLUS_T30;
          echo "<b> ";
          echo $this->data['gold_num'];
          echo "</b> ";
          echo LANGUI_PLUS_T31;
      } else {
          echo LANGUI_PLUS_T32;
      }
      echo "</p>\r\n<table class=\"plusFunctions\" cellpadding=\"1\" cellspacing=\"1\">\r\n\t<thead>\r\n\t\t<tr><th colspan=\"5\">";
      echo LANGUI_PLUS_T33;
      echo "</th></tr>\r\n\t\t<tr><td></td><td>";
      echo LANGUI_PLUS_T34;
      echo "</td><td>";
      echo text_period_lang;
      echo "</td><td>";
      echo LANGUI_PLUS_T2;
      echo "</td><td>";
      echo LANGUI_PLUS_T35;
      echo "</td></tr>\r\n\t</thead>\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td class=\"man\"><a href=\"#\" onclick=\"return showManual(5,0);\"><img class=\"help\" src=\"assets/x.gif\" alt=\"\" title=\"\"></a></td>\r\n\t\t\t<td class=\"desc\">\r\n\t\t\t\t<p><b><font color=\"#71D000\"> ";
      echo LANGUI_PLUS_T36;
      echo "  </p><br>\r\n\t\t\t\t";
      echo "<s";
      echo "pan class=\"run\">&nbsp;";
      echo $this->getRemainingPlusTime(0);
      echo "</span>\r\n\t\t\t</td>\r\n\t\t\t<td class=\"dur\">";
      echo $this->plusTable[0]['time'] == 0 ? LANGUI_PLUS_T37 : $this->plusTable[0]['time'] . " " . LANGUI_PLUS_T38;
      echo "</td>\r\n\t\t\t<td class=\"cost\"><img src=\"assets/x.gif\" class=\"gold\" alt=\"";
      echo LANGUI_PLUS_T6;
      echo "\" title=\"";
      echo LANGUI_PLUS_T6;
      echo "\">";
      echo $this->plusTable[0]['cost'];
      echo "</td>\r\n\t\t\t<td class=\"act\">";
      echo $this->getPlusAction(0);
      echo "</td>\r\n\t\t</tr>\t\r\n\t\t<tr>\r\n\t\t\t<td colspan=\"5\" class=\"empty\"></td>\r\n\t\t</tr>\r\n\t\t\r\n\t\t<tr>\r\n\t\t\t<td class=\"man\"><a href=\"#\" onclick=\"return showManual(5,1);\"><img class=\"help\" src=\"assets/x.gif\" alt=\"\" title=\"\"></a></td>\r\n\t\t\t<td class=\"desc\">\r\n\t\t\t\t+<b>25</b>% <img class=\"r1\" src=\"assets/x.gif\" alt=\"";
      echo item_title_1;
      echo "\" title=\"";
      echo item_title_1;
      echo "\"> ";
      echo LANGUI_PLUS_T39;
      echo "<br>\r\n\t\t\t\t";
      echo "<s";
      echo "pan class=\"run\">&nbsp;";
      echo $this->getRemainingPlusTime(1);
      echo "</span>\r\n\t\t\t</td>\r\n\t\t\t<td class=\"dur\">";
      echo $this->plusTable[1]['time'] == 0 ? LANGUI_PLUS_T37 : $this->plusTable[1]['time'] . " " . LANGUI_PLUS_T38;
      echo "</td>\r\n\t\t\t<td class=\"cost\"><img src=\"assets/x.gif\" class=\"gold\" alt=\"";
      echo LANGUI_PLUS_T6;
      echo "\" title=\"";
      echo LANGUI_PLUS_T6;
      echo "\">";
      echo $this->plusTable[1]['cost'];
      echo "</td>\r\n\t\t\t<td class=\"act\">";
      echo $this->getPlusAction(1);
      echo "</td>\r\n\t\t</tr>\r\n\t\r\n\t\t<tr>\r\n\t\t\t<td class=\"man\"><a href=\"#\" onclick=\"return showManual(5,2);\"><img class=\"help\" src=\"assets/x.gif\" alt=\"\" title=\"\"></a></td>\r\n\t\t\t<td class=\"desc\">\r\n\t\t\t\t+<b>25</b>% <img class=\"r2\" src=\"assets/x.gif\" alt=\"";
      echo item_title_2;
      echo "\" title=\"";
      echo item_title_2;
      echo "\"> ";
      echo LANGUI_PLUS_T40;
      echo "<br>\r\n\t\t\t\t";
      echo "<s";
      echo "pan class=\"run\">&nbsp;";
      echo $this->getRemainingPlusTime(2);
      echo "</span>\r\n\t\t\t</td>\r\n\t\t\t<td class=\"dur\">";
      echo $this->plusTable[2]['time'] == 0 ? LANGUI_PLUS_T37 : $this->plusTable[2]['time'] . " " . LANGUI_PLUS_T38;
      echo "</td>\r\n\t\t\t<td class=\"cost\"><img src=\"assets/x.gif\" class=\"gold\" alt=\"";
      echo LANGUI_PLUS_T6;
      echo "\" title=\"";
      echo LANGUI_PLUS_T6;
      echo "\">";
      echo $this->plusTable[2]['cost'];
      echo "</td>\r\n\t\t\t<td class=\"act\">";
      echo $this->getPlusAction(2);
      echo "</td>\r\n\t\t</tr>\r\n\t\r\n\t\t<tr>\r\n\t\t\t<td class=\"man\"><a href=\"#\" onclick=\"return showManual(5,3);\"><img class=\"help\" src=\"assets/x.gif\" alt=\"\" title=\"\"></a></td>\r\n\t\t\t<td class=\"desc\">\r\n\t\t\t\t+<b>25</b>% <img class=\"r3\" src=\"assets/x.gif\" alt=\"";
      echo item_title_3;
      echo "\" title=\"";
      echo item_title_3;
      echo "\"> ";
      echo LANGUI_PLUS_T41;
      echo "<br>\r\n\t\t\t\t";
      echo "<s";
      echo "pan class=\"run\">&nbsp;";
      echo $this->getRemainingPlusTime(3);
      echo "</span>\r\n\t\t\t</td>\r\n\t\t\t<td class=\"dur\">";
      echo $this->plusTable[3]['time'] == 0 ? LANGUI_PLUS_T37 : $this->plusTable[3]['time'] . " " . LANGUI_PLUS_T38;
      echo "</td>\r\n\t\t\t<td class=\"cost\"><img src=\"assets/x.gif\" class=\"gold\" alt=\"";
      echo LANGUI_PLUS_T6;
      echo "\" title=\"";
      echo LANGUI_PLUS_T6;
      echo "\">";
      echo $this->plusTable[3]['cost'];
      echo "</td>\r\n\t\t\t<td class=\"act\">";
      echo $this->getPlusAction(3);
      echo "</td>\r\n\t\t</tr>\r\n\t\r\n\t\t<tr>\r\n\t\t\t<td class=\"man\"><a href=\"#\" onclick=\"return showManual(5,4);\"><img class=\"help\" src=\"assets/x.gif\" alt=\"\" title=\"\"></a></td>\r\n\t\t\t<td class=\"desc\">\r\n\t\t\t\t+<b>25</b>% <img class=\"r4\" src=\"assets/x.gif\" alt=\"";
      echo item_title_4;
      echo "\" title=\"";
      echo item_title_4;
      echo "\"> ";
      echo LANGUI_PLUS_T42;
      echo "<br>\r\n\t\t\t\t";
      echo "<s";
      echo "pan class=\"run\">&nbsp;";
      echo $this->getRemainingPlusTime(4);
      echo "</span>\r\n\t\t\t</td>\r\n\t\t\t<td class=\"dur\">";
      echo $this->plusTable[4]['time'] == 0 ? LANGUI_PLUS_T37 : $this->plusTable[4]['time'] . " " . LANGUI_PLUS_T38;
      echo "</td>\r\n\t\t\t<td class=\"cost\"><img src=\"assets/x.gif\" class=\"gold\" alt=\"";
      echo LANGUI_PLUS_T6;
      echo "\" title=\"";
      echo LANGUI_PLUS_T6;
      echo "\">";
      echo $this->plusTable[4]['cost'];
      echo "</td>\r\n\t\t\t<td class=\"act\">";
      echo $this->getPlusAction(4);
      echo "</td>\r\n\t\t</tr>\r\n\t\r\n\t\t<tr>\r\n\t\t\t<td colspan=\"5\" class=\"empty\"></td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td class=\"man\"><a href=\"#\" onclick=\"return showManual(5,5);\"><img class=\"help\" src=\"assets/x.gif\" alt=\"\" title=\"\"></a></td>\r\n\t\t\t<td class=\"desc\">";
      echo LANGUI_PLUS_T43;
      echo "</td>\r\n\t\t\t<td class=\"dur\">";
      echo $this->plusTable[5]['time'] == 0 ? LANGUI_PLUS_T37 : $this->plusTable[5]['time'] . " " . LANGUI_PLUS_T38;
      echo "</td>";

echo "\r\n\t\t\t<td class=\"cost\"><img src=\"assets/x.gif\" class=\"gold\" alt=\"";
      echo LANGUI_PLUS_T6;
      echo "\" title=\"";
      echo LANGUI_PLUS_T6;
      echo "\">";
      echo $this->plusTable[5]['cost'];
      echo "</td>\r\n\t\t\t<td class=\"act\">";
      echo $this->getPlusAction(5);
      echo "</td>\r\n\t\t</tr>\t\r\n\t\t";
echo "<tr>\r\n\t\t\t<td class=\"man\"><a href=\"#\" onclick=\"return showManual(5,7);\"><img class=\"help\" src=\"assets/x.gif\" alt=\"\" title=\"\"></a></td>\r\n\t\t\t<td class=\"desc\">";
    echo LANGUI_PLUS_T44;
    echo "</td>\r\n\t\t\t<td class=\"dur\">";
    echo $this->plusTable[6]['time'] == 0 ? LANGUI_PLUS_T37 : $this->plusTable[6]['time']." ".LANGUI_PLUS_T38;
    echo "</td>\r\n\t\t\t<td class=\"cost\"><img src=\"assets/x.gif\" class=\"gold\" alt=\"";
    echo LANGUI_PLUS_T6;
    echo "\" title=\"";
    echo LANGUI_PLUS_T6;
    echo "\">";
    echo $this->plusTable[6]['cost'];
    echo "</td>\r\n\t\t\t<td class=\"act\">";
    echo $this->getPlusAction( 6 );
    echo "</td>\r\n\t\t</tr>";

    // add ( ذهب 25 ) إستكمال أوامر تدريب الجنود فورا إستكمال أوامر تدريب الجنود فورا
    echo "<tr>\r\n\t\t\t<td class=\"man\"><a href=\"#\" onclick=\"return showManual(5,8);\"><img class=\"help\" src=\"assets/x.gif\" alt=\"\" title=\"\"></a></td>\r\n\t\t\t<td class=\"desc\">";
    echo LANGUI_PLUS_T45;
    echo "</td>\r\n\t\t\t<td class=\"dur\">";
    echo $this->plusTable[7]['time'] == 0 ? LANGUI_PLUS_T37 : $this->plusTable[7]['time']." ".LANGUI_PLUS_T38;
    echo "</td>\r\n\t\t\t<td class=\"cost\"><img src=\"assets/x.gif\" class=\"gold\" alt=\"";
    echo LANGUI_PLUS_T6;
    echo "\" title=\"";
    echo LANGUI_PLUS_T6;
    echo "\">";
    echo $this->plusTable[7]['cost'];
    echo "</td>\r\n\t\t\t<td class=\"act\">";
    echo $this->getPlusAction( 7 );
    echo "</td>\r\n\t\t</tr>";
    // add رجوع التعزيزات فورا
    echo "<tr>\r\n\t\t\t<td class=\"man\"><a href=\"#\" onclick=\"return showManual(5,9);\"><img class=\"help\" src=\"assets/x.gif\" alt=\"\" title=\"\"></a></td>\r\n\t\t\t<td class=\"desc\">";
    echo "وصول جميع التعزيزات فورا";
    echo "</td>\r\n\t\t\t<td class=\"dur\">";
    echo $this->plusTable[8]['time'] == 0 ? LANGUI_PLUS_T37 : $this->plusTable[8]['time']." ".LANGUI_PLUS_T38;
    echo "</td>\r\n\t\t\t<td class=\"cost\"><img src=\"assets/x.gif\" class=\"gold\" alt=\"";
    echo LANGUI_PLUS_T6;
    echo "\" title=\"";
    echo LANGUI_PLUS_T6;
    echo "\">";
    echo 35;
    echo "</td>\r\n\t\t\t<td class=\"act\">";
    echo "<a href='plus.php?backtroops0'>تفعيل</a>";
    echo "</td>\r\n\t\t</tr>";
    



    echo "\t\r\n\t</tbody>\r\n</table>\r\n";
    echo "</p>\r\n";

}else if ($this->selectedTabIndex == 3) { 
    
}  else if ($this->selectedTabIndex == 4) { 
$t7 = $this->data['gold_num'] - 51000;
?>
يمكنك تحويل <b><?php if ($t7 <= 0) {echo "0";} else {echo $t7;} ?></b> من الذهب<br>
<form action="plus.php?t=4" method="post">
<table class="rate_details lang_rtl lang_ar" cellpadding="1" cellspacing="1">
<thead>
<tr>
                <th colspan="2">يمكنك تحويل الذهب من هنا الى لاعب اخر في نفس السيرفر</th>
</tr>
</thead>
<tbody>
<tr class="top">
                <td><?php echo LANGUI_TRANS_T3; ?></td>
                <td><input class="text" type="text" name="name" maxlength="20" value=""></td>
</tr>
<tr>
                <td><?php echo LANGUI_TRANS_T4; ?></td>
                <td><input class="text" type="text" name="gold" maxlength="10" value=""></td>
</tr>
<tr class="btm">
                <td><?php echo LANGUI_TRANS_T5; ?></td>
                <td><input class="text" type="password" name="pass" maxlength="25" value=""></td>
</tr>
</tbody>
</table>
<p class="btn"><center>
<input type="image" value="" name="s1" id="btn_send" class="dynamic_img" src="assets/x.gif">                        
</center></p>
</form>
<?php
if ( $this->errorTable != NULL ) { ?>
<p class="error"><? echo $this->errorTable;?></p>
<?php
 }
 }
?>