<?php

// check if the player has protection
require( APP_PATH."config.php" );
$link = mysql_connect($AppConfig['db']['host'],$AppConfig['db']['user'],$AppConfig['db']['password']) or die(mysql_error());
mysql_select_db($AppConfig['db']['database'],$link) or die(mysql_error());
$playerId = $this->player->playerId;

$query = mysql_query("SELECT * FROM p_players WHERE id = $playerId");
$row = mysql_fetch_array($query);
$registration_date = $row['registration_date'];
$date_now = date("Y-m-d H:i:s");
$diff = strtotime($date_now) - strtotime($registration_date);
$protection = $GLOBALS['GameMetadata']['player_protection_period'] / $GLOBALS['GameMetadata']['game_speed'];

// get how much protection in the setting


// check if the player has protection of 24 hours
if($diff < $protection) {
    echo "<br>";
    echo "<div class='error'>إنتباه : أنت تحت الحماية الآن</div>";
    echo '<p style="color: #FF5733; background-color: #F0F0F0; padding: 10px; border-radius: 5px; sans-serif; font-size: 14px;">
  <strong>ملاحظة مهمة:</strong>
عند مهاجمتك لاعبًا آخر أو استهدافك لواحة تحت ملكية شخص آخر بينما أنت تحت الحماية، ستُفقد حمايتك تلقائيًا، <b>حتى وإن كان الهدف هو معرفة وقت وصول الهجوم</b>. لذا، توخَّ الحذر عند القيام بهجمات تجريبية، فقد تتسبب في خسارة حمايتك دون قصد!</p>';

}




if ( $this->pageState == 1 )
{
    echo "<h1>";
    echo LANGUI_V2V_T1;
    echo "</h1>";
    echo "<p>";
    echo "\r\n\r\n<form method=\"post\" name=\"snd\" action=\"v2v.php\">\r\n";

?>

<div class="v2vStyle">
<div class="hadafAndIrssal">
    <table style="width: 100%; border: none !important;" cellpadding="1" cellspacing="1">
        <tbody>
            <tr>
                <td style="padding:8px;border-bottom: 1px solid #ddd; background:#eee;" colspan="3">
                <b>الهدف</b>
                    :</td>
                
            </tr>
            <tr>
                <td style="padding:8px;">
                    <input type="text" class="text" name="dname" value="" maxlength="20" placeholder="اسم القرية">
                </td>
            </tr>
            <tr>
                <td style="padding:8px;">
                    أو:</td>
            </tr>
            <tr>
                <td style="padding:8px;">
                    <table cellpadding="1" cellspacing="1" style="max-width: 100%;">
                        <tbody>
                        <tr>
                            <td>
                                X
                            </td>
                            <td>
                            <input type="text" class="text" style="width:23px" name="x" value="<?php if ( $this->targetVillage['x'] !== NULL ) { echo $this->targetVillage['x']; } ?>" maxlength="4">
                            </td>
                            <td>
                                Y
                            </td>
                            <td>
                            <input type="text" class="text" style="width:23px" name="y" value="<?php if ( $this->targetVillage['y'] !== NULL ) { echo $this->targetVillage['y']; } ?>" maxlength="4">
                            </td>
                            
                        </tr>
                        </tbody>
                    </table>

                </td>
            </tr>
            <tr>
                <td style="padding:8px;border-bottom: 1px solid #ddd; background:#eee;" colspan="3"><b>
                نوع الإرسال:</b></td>
            </tr>


            <tr>


            <td style="padding:8px;">
                <label>
                    <input type="radio" class="radio" name="c" value="2"
                        <?php if ($this->disableFirstTwoAttack) { ?>
                            disabled="disabled"
                        <?php } else if ($this->transferType == 2) { ?>
                            checked=""
                        <?php } ?>
                    > 
                    <?php echo LANGUI_V2V_T2; ?>
                </label>
            </td>

            </tr>

            

            <tr>

            <td style="padding:8px;">
                <label>
                    <input type="radio" class="radio" name="c" value="3"
                        <?php if ($this->disableFirstTwoAttack) { ?>
                            disabled="disabled"
                        <?php } else if ($this->transferType == 3) { ?>
                            checked=""
                        <?php } ?>
                    > 
                    <?php echo LANGUI_V2V_T4; ?>
                </label>
            </td>
        </tr>


        <tr>
            <td style="padding:8px;">
                <label>
                    <input type="radio" class="radio" name="c" value="4"
                        <?php if ($this->disableFirstTwoAttack || $this->transferType == 4) { ?>
                            checked=""
                        <?php } ?>
                    > 
                    <?php echo LANGUI_V2V_T5; ?>
                </label>
            </td>
        </tr>
        </tbody>
    </table>
</div>

    <div class="alqowat">
        <table style="width: 100%; border: none !important;" cellpadding="1" cellspacing="1">
            <tbody>
                <tr>
                    <td style="padding:8px;border-bottom: 1px solid #ddd; background:#eee;" colspan="3">
                    <b>القوات</b>
                        :</td>
                </tr>
            <tr>
                <td style="padding:8px;">
                    <table cellpadding="1" cellspacing="1">
                        <tbody>
                        <tr>
                            <td>
                                <img class="unit u<?php echo $this->troops[0]['troopId']; ?>" src="assets/x.gif" title="<?php echo constant( "troop_".$this->troops[0]['troopId'] ); ?>" alt="<?php echo constant( "troop_".$this->troops[0]['troopId'] ); ?>"<?php if ( 0 < $this->troops[0]['number'] ) { echo " onclick=\"_('t1').value=''; return false;\""; } ?>> 
                            </td>
                            <td>
                                <input type="text" class="text<?php if ( $this->troops[0]['number'] <= 0 ) { echo " disabled"; } ?>" name="t[<?php echo $this->troops[0]['troopId']; ?>]" id="t1" value="" maxlength="10"> 
                            </td>
                            <td>    
                                <?php if ( $this->troops[0]['number'] <= 0 ) { echo "<span class=\"none\">(0)</span>"; } else { echo "<a href=\"#\" onclick=\"_('t1').value=".$this->troops[0]['number']."; return false;\">(".$this->troops[0]['number'].")</a>"; } ?>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                
            </td>
            
            </tr>
            <tr>
                <td style="padding:8px;">
                    <table cellpadding="1" cellspacing="1">
                        <tbody>
                        <tr>
                            <td>
                                <img class="unit u<?php echo $this->troops[1]['troopId']; ?>" src="assets/x.gif" title="<?php echo constant( "troop_".$this->troops[1]['troopId'] ); ?>" alt="<?php echo constant( "troop_".$this->troops[1]['troopId'] ); ?>"<?php if ( 0 < $this->troops[1]['number'] ) { echo " onclick=\"_('t2').value=''; return false;\""; } ?>> 
                            </td>
                            <td>
                                <input type="text" class="text<?php if ( $this->troops[1]['number'] <= 0 ) { echo " disabled"; } ?>" name="t[<?php echo $this->troops[1]['troopId']; ?>]" id="t2" value="" maxlength="10"> 
                            </td>
                            <td>    
                                <?php if ( $this->troops[1]['number'] <= 0 ) { echo "<span class=\"none\">(0)</span>"; } else { echo "<a href=\"#\" onclick=\"_('t2').value=".$this->troops[1]['number']."; return false;\">(".$this->troops[1]['number'].")</a>"; } ?>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td style="padding:8px;">
                    <table cellpadding="1" cellspacing="1">
                        <tbody>
                        <tr>
                            <td>
                                <img class="unit u<?php echo $this->troops[2]['troopId']; ?>" src="assets/x.gif" title="<?php echo constant( "troop_".$this->troops[2]['troopId'] ); ?>" alt="<?php echo constant( "troop_".$this->troops[2]['troopId'] ); ?>"<?php if ( 0 < $this->troops[2]['number'] ) { echo " onclick=\"_('t3').value=''; return false;\""; } ?>> 
                            </td>
                            <td>
                                <input type="text" class="text<?php if ( $this->troops[2]['number'] <= 0 ) { echo " disabled"; } ?>" name="t[<?php echo $this->troops[2]['troopId']; ?>]" id="t3" value="" maxlength="10"> 
                            </td>
                            <td>    
                                <?php if ( $this->troops[2]['number'] <= 0 ) { echo "<span class=\"none\">(0)</span>"; } else { echo "<a href=\"#\" onclick=\"_('t3').value=".$this->troops[2]['number']."; return false;\">(".$this->troops[2]['number'].")</a>"; } ?>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td style="padding:8px;">
                    <table cellpadding="1" cellspacing="1">
                        <tbody>
                        <tr>
                            <td>
                                <img class="unit u<?php echo $this->troops[3]['troopId']; ?>" src="assets/x.gif" title="<?php echo constant( "troop_".$this->troops[3]['troopId'] ); ?>" alt="<?php echo constant( "troop_".$this->troops[3]['troopId'] ); ?>"<?php if ( 0 < $this->troops[3]['number'] ) { echo " onclick=\"_('t4').value=''; return false;\""; } ?>> 
                            </td>
                            <td>
                                <input type="text" class="text<?php if ( $this->troops[3]['number'] <= 0 ) { echo " disabled"; } ?>" name="t[<?php echo $this->troops[3]['troopId']; ?>]" id="t4" value="" maxlength="10"> 
                            </td>
                            <td>    
                                <?php if ( $this->troops[3]['number'] <= 0 ) { echo "<span class=\"none\">(0)</span>"; } else { echo "<a href=\"#\" onclick=\"_('t4').value=".$this->troops[3]['number']."; return false;\">(".$this->troops[3]['number'].")</a>"; } ?>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td style="padding:8px;">
                    <table cellpadding="1" cellspacing="1">
                        <tbody>
                        <tr>
                            <td>
                                <img class="unit u<?php echo $this->troops[4]['troopId']; ?>" src="assets/x.gif" title="<?php echo constant( "troop_".$this->troops[4]['troopId'] ); ?>" alt="<?php echo constant( "troop_".$this->troops[4]['troopId'] ); ?>"<?php if ( 0 < $this->troops[4]['number'] ) { echo " onclick=\"_('t5').value=''; return false;\""; } ?>> 
                            </td>
                            <td>
                                <input type="text" class="text<?php if ( $this->troops[4]['number'] <= 0 ) { echo " disabled"; } ?>" name="t[<?php echo $this->troops[4]['troopId']; ?>]" id="t5" value="" maxlength="10"> 
                            </td>
                            <td>    
                                <?php if ( $this->troops[4]['number'] <= 0 ) { echo "<span class=\"none\">(0)</span>"; } else { echo "<a href=\"#\" onclick=\"_('t5').value=".$this->troops[4]['number']."; return false;\">(".$this->troops[4]['number'].")</a>"; } ?>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td style="padding:8px;">
                    <table cellpadding="1" cellspacing="1">
                        <tbody>
                        <tr>
                            <td>
                                <img class="unit u<?php echo $this->troops[5]['troopId']; ?>" src="assets/x.gif" title="<?php echo constant( "troop_".$this->troops[5]['troopId'] ); ?>" alt="<?php echo constant( "troop_".$this->troops[5]['troopId'] ); ?>"<?php if ( 0 < $this->troops[5]['number'] ) { echo " onclick=\"_('t6').value=''; return false;\""; } ?>> 
                            </td>
                            <td>
                                <input type="text" class="text<?php if ( $this->troops[5]['number'] <= 0 ) { echo " disabled"; } ?>" name="t[<?php echo $this->troops[5]['troopId']; ?>]" id="t6" value="" maxlength="10"> 
                            </td>
                            <td>    
                                <?php if ( $this->troops[5]['number'] <= 0 ) { echo "<span class=\"none\">(0)</span>"; } else { echo "<a href=\"#\" onclick=\"_('t6').value=".$this->troops[5]['number']."; return false;\">(".$this->troops[5]['number'].")</a>"; } ?>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td style="padding:8px;">
                    <table cellpadding="1" cellspacing="1">
                        <tbody>
                        <tr>
                            <td>
                                <img class="unit u<?php echo $this->troops[6]['troopId']; ?>" src="assets/x.gif" title="<?php echo constant( "troop_".$this->troops[6]['troopId'] ); ?>" alt="<?php echo constant( "troop_".$this->troops[6]['troopId'] ); ?>"<?php if ( 0 < $this->troops[6]['number'] ) { echo " onclick=\"_('t7').value=''; return false;\""; } ?>> 
                            </td>
                            <td>
                                <input type="text" class="text<?php if ( $this->troops[6]['number'] <= 0 ) { echo " disabled"; } ?>" name="t[<?php echo $this->troops[6]['troopId']; ?>]" id="t7" value="" maxlength="10"> 
                            </td>
                            <td>    
                                <?php if ( $this->troops[6]['number'] <= 0 ) { echo "<span class=\"none\">(0)</span>"; } else { echo "<a href=\"#\" onclick=\"_('t7').value=".$this->troops[6]['number']."; return false;\">(".$this->troops[6]['number'].")</a>"; } ?>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td style="padding:8px;">
                    <table cellpadding="1" cellspacing="1">
                        <tbody>
                        <tr>
                            <td>
                                <img class="unit u<?php echo $this->troops[7]['troopId']; ?>" src="assets/x.gif" title="<?php echo constant( "troop_".$this->troops[7]['troopId'] ); ?>" alt="<?php echo constant( "troop_".$this->troops[7]['troopId'] ); ?>"<?php if ( 0 < $this->troops[7]['number'] ) { echo " onclick=\"_('t8').value=''; return false;\""; } ?>> 
                            </td>
                            <td>
                                <input type="text" class="text<?php if ( $this->troops[7]['number'] <= 0 ) { echo " disabled"; } ?>" name="t[<?php echo $this->troops[7]['troopId']; ?>]" id="t8" value="" maxlength="10"> 
                            </td>
                            <td>    
                                <?php if ( $this->troops[7]['number'] <= 0 ) { echo "<span class=\"none\">(0)</span>"; } else { echo "<a href=\"#\" onclick=\"_('t8').value=".$this->troops[7]['number']."; return false;\">(".$this->troops[7]['number'].")</a>"; } ?>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td style="padding:8px;">
                    <table cellpadding="1" cellspacing="1">
                        <tbody>
                        <tr>
                            <td>
                                <img class="unit u<?php echo $this->troops[8]['troopId']; ?>" src="assets/x.gif" title="<?php echo constant( "troop_".$this->troops[8]['troopId'] ); ?>" alt="<?php echo constant( "troop_".$this->troops[8]['troopId'] ); ?>"<?php if ( 0 < $this->troops[8]['number'] ) { echo " onclick=\"_('t9').value=''; return false;\""; } ?>> 
                            </td>
                            <td>
                                <input type="text" class="text<?php if ( $this->troops[8]['number'] <= 0 ) { echo " disabled"; } ?>" name="t[<?php echo $this->troops[8]['troopId']; ?>]" id="t9" value="" maxlength="10"> 
                            </td>
                            <td>    
                                <?php if ( $this->troops[8]['number'] <= 0 ) { echo "<span class=\"none\">(0)</span>"; } else { echo "<a href=\"#\" onclick=\"_('t9').value=".$this->troops[8]['number']."; return false;\">(".$this->troops[8]['number'].")</a>"; } ?>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td style="padding:8px;">
                    <table cellpadding="1" cellspacing="1">
                        <tbody>
                        <tr>
                            <td>
                                <img class="unit u<?php echo $this->troops[9]['troopId']; ?>" src="assets/x.gif" title="<?php echo constant( "troop_".$this->troops[9]['troopId'] ); ?>" alt="<?php echo constant( "troop_".$this->troops[9]['troopId'] ); ?>"<?php if ( 0 < $this->troops[9]['number'] ) { echo " onclick=\"_('t10').value=''; return false;\""; } ?>> 
                            </td>
                            <td>
                                <input type="text" class="text<?php if ( $this->troops[9]['number'] <= 0 ) { echo " disabled"; } ?>" name="t[<?php echo $this->troops[9]['troopId']; ?>]" id="t10" value="" maxlength="10"> 
                            </td>
                            <td>    
                                <?php if ( $this->troops[9]['number'] <= 0 ) { echo "<span class=\"none\">(0)</span>"; } else { echo "<a href=\"#\" onclick=\"_('t10').value=".$this->troops[9]['number']."; return false;\">(".$this->troops[9]['number'].")</a>"; } ?>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            
            <?php if ( $this->hasHero ) { ?>
            <tr>
                <td style="padding:8px;">
                    <table cellpadding="1" cellspacing="1">
                        <tbody>
                        <tr>
                            <td>
                            <img class="unit uhero" src="assets/x.gif" title="<?php echo troop_hero; ?>" 
     onclick="document.getElementById('_t').value=''; return false;" 
     alt="<?php echo troop_hero; ?>">
                            </td>
                            <td>
                            <input type="text" class="text" id="_t" name="_t" value="" maxlength="1">
                            </td>
                            <td>
                            <a href="#" onclick="_('_t').value=1; return false;">(1)</a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </td>
        </tr>
        <?php } ?>

            
                
        </tbody>
    </table>


    </div>

   

</div>
        <p style="margin-top: 20px;margin-bottom: 20px;text-align: center;">
            
        <button type="submit" style="
    padding: 1px;
    border-radius: 5px;
    padding-left: 20px;
    padding-right: 20px;
    border: 1px solid #71d000;
    background-image: linear-gradient(to bottom, #fdfdfd, #c6c6c6);
    cursor: pointer;
    color: #7a7a7a;
    text-align: center;
    font-weight: 700;
    text-shadow: none;
"
name="s1" id="btn_ok" value="ok" id="btn_ok" onClick="this.style.visibility='hidden'; "
>إرسال القوات
        </button>

            </p>

</form>
<?php
if ( $this->errorTable != NULL )
    {
        echo "<p class=\"error\">";
        echo $this->errorTable;
        echo "</p>";
    }
echo "</p>";
}

else if ( $this->pageState == 2 )
{
    echo "<h1><p>";
    echo $this->targetVillage['transferType'];
    echo "</p></h1>\r\n<form method=\"post\" name=\"snd\" style='overflow-x:auto;' action=\"v2v.php?t=2\">\r\n<table id=\"short_info\" cellpadding=\"1\" cellspacing=\"1\">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<th>";
    echo LANGUI_V2V_T6;
    echo ":</th>\r\n\t\t\t<td><a href=\"village3.php?id=";
    echo $this->targetVillage['villageId'];
    echo "\">";
    echo $this->targetVillage['villageName'];
    echo "</a></td>\r\n\t\t</tr>\r\n\t\t";
    if ( trim( $this->targetVillage['playerName'] ) != "" )
    {
        echo "\t\t<tr>\r\n\t\t\t<th>";
        echo LANGUI_V2V_T7;
        echo ":</th>\r\n\t\t\t<td>";
        if ( $this->targetVillage['playerId'] == 0 )
        {
            echo $this->targetVillage['playerName'];
        }
        else
        {
            echo "<a href=\"profile.php?uid=";
            echo $this->targetVillage['playerId'];
            echo "\">";
            echo $this->targetVillage['playerName'];
            echo "</a>";
        }
        echo "</td>\r\n\t\t</tr>\r\n\t\t";
    }
    echo "\t</tbody>\r\n</table>\r\n\r\n<table class=\"troop_details\" cellpadding=\"1\" cellspacing=\"1\">\r\n\t<thead>\r\n\t\t<tr>\r\n\t\t\t<td>";
    echo $this->data['village_name'];
    echo "</td>\r\n\t\t\t<td colspan=\"11\"><p class=\"custDir\">";
    echo $this->targetVillage['transferType']." ".$this->targetVillage['playerName'];
    echo "</p></td>\r\n\t\t</tr>\r\n\t</thead>\r\n\t<tbody class=\"units\">\r\n\t\t<tr>\r\n\t\t\t<td></td>\r\n\t\t\t";
    foreach ( $this->targetVillage['troops'] as $tid => $tnum )
    {
        echo "\t\t\t<td><img src=\"assets/x.gif\" class=\"unit u";
        echo $tid;
        echo "\" title=\"";
        echo constant( "troop_".$tid );
        echo "\" alt=\"";
        echo constant( "troop_".$tid );
        echo "\"></td>\r\n\t\t\t";
    }
    echo "\t\t\t";
    if ( $this->targetVillage['hasHero'] )
    {
        echo "\t\t\t<td><img src=\"assets/x.gif\" class=\"unit uhero\" title=\"";
        echo troop_hero;
        echo "\" alt=\"";
        echo troop_hero;
        echo "\"></td>\r\n\t\t\t";
    }
    echo "\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<th>";
    echo LANGUI_V2V_T8;
    echo "</th>\r\n\t\t\t";
    foreach ( $this->targetVillage['troops'] as $tid => $tnum )
    {
        echo "\t\t\t\t";
        if ( $tnum <= 0 )
        {
            echo "<td class=\"none\">0</td>";
        }
        else
        {
            echo "<td>";
            echo $tnum;
            echo "</td>";
        }
        echo "\t\t\t";
    }
    echo "\t\t\t";
    if ( $this->targetVillage['hasHero'] )
    {
        echo "\t\t\t\t<td>1</td>\r\n\t\t\t";
    }
    echo "\r\n\t\t</tr>\r\n\t</tbody>\r\n\t";
    if ( $this->transferType == 1 )
    {
        echo "\t<tbody class=\"options\">\r\n\t\t<tr>\r\n\t\t\t<th>";
        echo LANGUI_V2V_T9;
        echo "</th>\r\n\t\t\t<td colspan=\"11\">\r\n\t\t\t\t<img class=\"r1\" src=\"assets/x.gif\" alt=\"";
        echo item_title_1;
        echo "\" title=\"";
        echo item_title_1;
        echo "\">";
        echo $this->newVillageResources[1];
        echo " | \r\n\t\t\t\t<img class=\"r2\" src=\"assets/x.gif\" alt=\"";
        echo item_title_2;
        echo "\" title=\"";
        echo item_title_2;
        echo "\">";
        echo $this->newVillageResources[2];
        echo " | \r\n\t\t\t\t<img class=\"r3\" src=\"assets/x.gif\" alt=\"";
        echo item_title_3;
        echo "\" title=\"";
        echo item_title_3;
        echo "\">";
        echo $this->newVillageResources[3];
        echo " | \r\n\t\t\t\t<img class=\"r4\" src=\"assets/x.gif\" alt=\"";
        echo item_title_4;
        echo "\" title=\"";
        echo item_title_4;
        echo "\">";
        echo $this->newVillageResources[4];
        echo "\t\t\t</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n\t";
    }
    else if ( $this->targetVillage['spy'] )
    {
        echo "\t<tbody class=\"options\">\r\n\t\t<tr>\r\n\t\t\t<th>";
        echo LANGUI_V2V_T10;
        echo "</th>\r\n\t\t\t<td colspan=\"11\">\r\n\t\t\t\t<input class=\"radio\" type=\"radio\" name=\"spy\" value=\"1\" checked=\"\">";
        echo LANGUI_V2V_T11;
        echo "<br>\r\n\t\t\t\t";
        if ( !$this->onlyOneSpyAction )
        {
            echo "<input class=\"radio\" type=\"radio\" name=\"spy\" value=\"2\">";
            echo LANGUI_V2V_T12;
        }
        echo "\t\t\t</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n\t";
    }
    else if ( $this->attackWithCatapult )
    {
        echo "\t<tbody class=\"options\">\r\n\t\t<tr>\r\n\t\t\t<th>";
        echo LANGUI_V2V_T6;
        echo "</th>\r\n\t\t\t<td colspan=\"11\">\r\n\t\t\t\t";
        echo "<s";
        echo "elect name=\"dtg\" class=\"dropdown\">\r\n\t\t\t\t\t <option value=\"99\">";
        echo LANGUI_V2V_T13;
        echo "</option>\r\n\t\t\t\t\t ";
        echo $this->availableCatapultTargetsString;
        echo "\t\t\t\t</select>\r\n\t\t\t\t";
        echo "<s";
        echo "pan class=\"info\">(";
        echo LANGUI_V2V_T14;
        echo ")</span>\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n\t";
        if ( $this->rallyPointLevel == 20 && 20 <= $this->totalCatapultTroopsCount )
        {
            echo "\t<tbody class=\"options\">\r\n\t\t<tr>\r\n\t\t\t<th>";
            echo LANGUI_V2V_T15;
            echo "</th>\r\n\t\t\t<td colspan=\"11\">\r\n\t\t\t\t";
            echo "<s";
            echo "elect name=\"dtg1\" class=\"dropdown\">\r\n\t\t\t\t\t <option value=\"99\">";
            echo LANGUI_V2V_T13;
            echo "</option>\r\n\t\t\t\t\t ";
            echo $this->availableCatapultTargetsString;
            echo "\t\t\t\t</select>\r\n\t\t\t\t";
            echo "<s";
            echo "pan class=\"info\">(";
            echo LANGUI_V2V_T14;
            echo ")</span>\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n\t";
        }
        echo "\t";
    }
    echo "\t<tbody class=\"infos\">\r\n\t\t<tr>\r\n\t\t\t<th>";
    echo LANGUI_V2V_T16;
    echo "</th>\r\n\t\t\t<td colspan=\"11\">";
    echo text_in_lang;
    echo " ";
    echo WebHelper::secondstostring( $this->targetVillage['needed_time'] );
    echo " ";
    echo LANGUI_V2V_T17;
echo " <div class='at small'>الوصول
<span id='timer2'>
".(date("G:i:s",time()+$this->targetVillage['needed_time']));
                echo "</span> ساعه </div>";
    echo "</td>\r\n\t\t</tr>\r\n\t";
/*
    echo "\t<tbody class=\"infos\">\r\n\t\t<tr>\r\n\t\t\t<th>";
    echo 'كود التحقق <img src="captcha.php">';
    echo "</th>\r\n\t\t\t<td colspan=\"11\">";
echo '<input class="text" type="text" name="Cap" maxlength="20">';
    echo "</td>\r\n\t\t</tr>\r\n\t";
*/
echo "</tbody>\r\n</table>\r\n\r\n<input  type=\"hidden\" name=\"id\" value=\"";
    echo $this->targetVillage['villageId'];
    echo "\">\r\n<input type=\"hidden\" name=\"c\" value=\"";
    echo isset( $_POST['c'] ) ? $_POST['c'] : 4;
    echo "\">\r\n";
    foreach ( $this->targetVillage['troops'] as $tid => $tnum )
    {
        echo "<input type=\"hidden\" name=\"t[";
        echo $tid;
        echo "]\" value=\"";
        echo $tnum;
        echo "\">\r\n";
    }
    if ( $this->targetVillage['hasHero'] )
    {
        echo "<input type=\"hidden\" name=\"_t\" value=\"1\">\r\n";
    }
    echo "<p class=\"btn\"><input type=\"image\" value=\"ok\" onClick=\"this.style.visibility='hidden';\" name=\"s1\" id=\"btn_ok\" class=\"dynamic_img\" src=\"assets/x.gif\" alt=\"";
    echo text_okdone_lang;
    echo "\"></p>";
echo " \r\n</form>\r\n";

    }
else if ( $this->pageState == 3 )
{
    $colspan = $this->backTroopsProperty['backTroops']['hasHero'] ? 11 : 10;
    echo "<h1>";
    echo $this->backTroopsProperty['headerText'];
    echo "</h1>\r\n<form method=\"POST\" action=\"v2v.php?";
    echo $this->backTroopsProperty['queryString'];
    echo "\">\r\n<table class=\"troop_details\" cellpadding=\"1\" cellspacing=\"1\">\r\n\t<thead>\r\n\t\t<tr>\r\n\t\t\t<td class=\"role\">";
    echo $this->backTroopsProperty['action1'];
    echo "</td>\r\n\t\t\t<td colspan=\"";
    echo $colspan;
    echo "\">";
    echo $this->backTroopsProperty['action2'];
    echo "</td>\r\n\t\t</tr>\r\n\t</thead>\r\n\t<tbody class=\"units\">\r\n\t\t<tr>\r\n\t\t\t<th>&nbsp;</th>\r\n\t\t\t";
    foreach ( $this->backTroopsProperty['backTroops']['troops'] as $tid => $tnum )
    {
        echo "\t\t\t<td><img src=\"assets/x.gif\" class=\"unit u";
        echo $tid;
        echo "\" title=\"";
        echo constant( "troop_".$tid );
        echo "\" alt=\"";
        echo constant( "troop_".$tid );
        echo "\"></td>\r\n\t\t\t";
    }
    echo "\t\t\t";
    if ( $this->backTroopsProperty['backTroops']['hasHero'] )
    {
        echo "\t\t\t<td><img src=\"assets/x.gif\" class=\"unit uhero\" title=\"";
        echo troop_hero;
        echo "\" alt=\"";
        echo troop_hero;
        echo "\"></td>\r\n\t\t\t";
    }
    echo "\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<th>";
    echo LANGUI_V2V_T8;
    echo "</th>\r\n\t\t\t";
    foreach ( $this->backTroopsProperty['backTroops']['troops'] as $tid => $tnum )
    {
        echo "\t\t\t\t";
        if ( $tnum <= 0 )
        {
            echo "<td class=\"none\">0</td>";
        }
        else
        {
            echo "<td><input type=\"text\" name=\"t[";
            echo $tid;
            echo "]\" class=\"text\" value=\"";
            echo $tnum;
            echo "\" maxlength=\"5\"></td>";
        }
        echo "\t\t\t";
    }
    echo "\t\t\t";
    if ( $this->backTroopsProperty['backTroops']['hasHero'] )
    {
        echo "\t\t\t\t<td><input type=\"text\" name=\"_t\" class=\"text\" value=\"1\" maxlength=\"5\"></td>\r\n\t\t\t";
    }
    echo "\t\t</tr>\r\n\t</tbody>\r\n\t<tbody class=\"infos\">\r\n\t\t<tr>\r\n\t\t\t<th>";
    echo LANGUI_V2V_T16;
    echo "</th>\r\n\t\t\t<td colspan=\"";
    echo $colspan;
    echo "\"><div class=\"in\">";
    echo text_in_lang;
    echo " ";
    echo WebHelper::secondstostring( $this->backTroopsProperty['time'] );
    echo " ";
    echo LANGUI_V2V_T17;
    echo "</div>";
    echo " <div class='at small'>الوصول
<span id='timer2'>
".(date("G:i:s",time()+$this->backTroopsProperty['time']));
                echo "</span> ساعه </div>";
 echo "</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n\r\n<p class=\"btn\"><input type=\"image\" value=\"ok\" onClick=\"this.style.visibility='hidden'\" name=\"s1\" id=\"btn_ok\" class=\"dynamic_img\" src=\"assets/x.gif\" alt=\"";
    echo text_okdone_lang;
    echo "\"></p>\r\n</form>\r\n";


    
}
?>