<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<title><?php echo $this->appConfig["page"][
    $this->appConfig["system"]["lang"] . "_title"
]; ?></title>
<meta http-equiv="cache-control" content="max-age=0" />
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="expires" content="0" />
<meta http-equiv="imagetoolbar" content="no" />
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<meta content="<?php echo $this->appConfig["page"][
    "meta-tag"
]; ?>" name="keywords">
<link href="assets/default/lang/sa<?php echo "/lang.css" .
    $this->getAssetVersion(); ?>" rel="stylesheet" type="text/css" />
<link href="assets/default/lang/sa<?php echo "/compact.css" .
    $this->getAssetVersion(); ?>" rel="stylesheet" type="text/css" />
<?php
echo "<script src=\"assets/mt-full.js\"  type=\"text/javascript\"></script>";
echo "<script src=\"assets/new.js\" type=\"text/javascript\"></script>";
?>
<meta name="google-site-verification" content="vTjsRxnpRzHRJvw5E3uOiAA-jcGayHNOw_SEAD93-fc" />
<link rel="shortcut icon" href="assets/favicon.ico" type="image/x-icon" />
<script type="text/javascript">var d3l=<?php echo $this->appConfig["system"][
    "lang"
] == "ar"
    ? "180"
    : "-600"; ?></script>
<script src="assets/core.js<?php echo $this->getAssetVersion(); ?>" type="text/javascript"></script>
<link rel="stylesheet" href="assets/responsive.css">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body class="v35 webkit">
<div class="wrapper">
<img src="assets/x.gif" id="msfilter" alt="" />
<div id="dynamic_header"></div>
<div id="header">
<div id="mtop" style="width: 600px;">
<?php if ($this->player != null) {
    if ($this->data["player_type"] == PLAYERTYPE_ADMIN) {
        echo '<a href="village1.php?admingwarhi" id="n1" accesskey="1">';
    } else {
        echo '<a href="village1.php" id="n1" accesskey="1">';
    }
    echo '<img src="assets/x.gif" title="' .
        LANGUI_GAME_ICO1 .
        '" alt="' .
        LANGUI_GAME_ICO1 .
        '" /></a>
<a href="village2.php" id="n2" accesskey="2"><img src="assets/x.gif" title="' .
        LANGUI_GAME_ICO2 .
        '" alt="' .
        LANGUI_GAME_ICO2 .
        '" /></a>
<a href="map.php" id="n3" accesskey="3"><img src="assets/x.gif" title="' .
        LANGUI_GAME_ICO3 .
        '" alt="' .
        LANGUI_GAME_ICO3 .
        '" /></a>
<a href="statistics.php" id="n4" accesskey="4"><img src="assets/x.gif" title="' .
        LANGUI_GAME_ICO4 .
        '" alt="' .
        LANGUI_GAME_ICO4 .
        '" /></a>
<div id="n5" class="i' .
        $this->reportMessageStatus .
        '">
<a class="reports" href="report.php" accesskey="5"><img src="assets/x.gif" class="l" title="' .
        LANGUI_GAME_ICO5 .
        '" alt="' .
        LANGUI_GAME_ICO5 .
        '" /></a>
<a class="messages" href="msg.php" accesskey="6"><img src="assets/x.gif" class="r" title="' .
        LANGUI_GAME_ICO6 .
        '" alt="' .
        LANGUI_GAME_ICO6 .
        '" /></a>
</div>';
    ?>

<?php
} ?>
<a href="plus.php" id="plus" style="background: none;display: block; font-size: 13px; height: 40px; padding-right: 12px; padding-top: 21px; position: relative; width: 120px;">
    <b>
        <font style="padding: 5px 10px;border: 1px solid rgb(255, 111, 15); border-top-left-radius: 10px; border-bottom-right-radius: 10px;" color="#FF6F0F">
            <?= $this->data["gold_num"] ?>
            <img src="assets/x.gif" class="gold" alt="gold">
        </font>
    </b>
</a>
        
</div>
</div>

<div id="resTop" style="display: none;">
    <div class="flex-container">
        <div class="flex-item">
            <img src="assets/x.gif" class="r1" title="<?php echo item_title_1; ?>" />
            <div id="l44" title="<?php echo $this->resources[1][
                "calc_prod_rate"
            ]; ?>">
                <?php echo $this->resources[1]["current_value"]; ?>
                <span style="display: none;"><?php echo '/' . $this->resources[1]['store_max_limit']; ?></span> 
            </div>
        </div>

        <div class="flex-item">
            <img src="assets/x.gif" class="r2" title="<?php echo item_title_2; ?>" />
            <div id="l33"  title="<?php echo $this->resources[2][
                "calc_prod_rate"
            ]; ?>">
                <?php echo $this->resources[2]["current_value"]; ?>
                <span style="display: none;"><?php echo '/' . $this->resources[2]['store_max_limit']; ?></span> 
            </div>
        </div>

        <div class="flex-item">
            <img src="assets/x.gif" class="r3" title="<?php echo item_title_3; ?>" />
            <div id="l22"  title="<?php echo $this->resources[3][
                "calc_prod_rate"
            ]; ?>">
                <?php echo $this->resources[3]["current_value"]; ?>
                <span style="display: none;"><?php echo '/' . $this->resources[3]['store_max_limit']; ?></span> 
            </div>
        </div>

        <div class="flex-item">
            <img src="assets/x.gif" class="r4" title="<?php echo item_title_4; ?>" />
            <div id="l11" title="<?php echo $this->resources[4][
                "calc_prod_rate"
            ]; ?>">
                <?php echo $this->resources[4]["current_value"]; ?>
                <span style="display: none;"><?php echo '/' . $this->resources[4]['store_max_limit']; ?></span> 
            </div>
        </div>

    </div>
</div>

<div id="mid">
<div id="side_navi">
<?php
require_once MODEL_PATH . "index.php";
$m1 = new IndexModel();
$this->datastats = $m1->getIndexSummary();
$m1->dispose();
echo '<br>';echo '<br>';

echo "<p><a href=\"index.php\">";
echo LANGUI_GAME_MENU1;
echo "</a>";
if ($this->player != null) {
    echo "
<a href=\"profile.php\">";
    echo LANGUI_GAME_MENU3;
    echo "</a>";
    echo "
<a href=\"logout.php\">";
    echo LANGUI_GAME_MENU4;
    echo "</a>
<br>";

    if ($this->data["player_type"] == PLAYERTYPE_ADMIN) {
        echo "<p> <a href=\"gamal11111.php\">";
        echo LANGUI_GAME_MENU13;
        echo "</a>
<a href=\"adminweb.php\">";
        echo "ادارة اللعبه";
        echo "</a><p>";
    }

    echo "<a href=\"farm.php\">";
    echo 'قائمة <b><font color="#71D000">المزارع</font><font color="#FF6F0F"></font><font color="#71D000"></font><font color="#FF6F0F"></font></b>';
    echo "</a>";
    echo "<a href=\"chat.php\">الشات</a>";
    echo "<a href=\"msg.php?uid=1\"><b>";
    echo '<font style="color: rgb(0, 0, 255);">الدعم</font>';
    echo "</b></a>";
}
echo "<p>";
$postfix = 0 < $this->dataGame["protection_remain_sec"] ? "" : "d";
if ($postfix == "d") {
    echo "";
} else {
    echo "ستنتهي الحمايه بعد ";
    echo "<b><span id=\"timer1\">";
    echo WebHelper::secondsToString($this->dataGame["protection_remain_sec"]);
    echo "</span></b>";
    echo " ساعه";
}

if ($this->player != null && $this->isPlayerInDeletionProgress()) {
    echo "<p class=\"deltimer\"><a href=\"profile.php?t=4\">";
    echo LANGUI_GAME_PLAYERDEL;
    echo " ";
    echo "<span id=\"timer1\">";
    echo $this->getPlayerDeletionTime();
    echo "</span>";
    echo time_hour_lang;
    echo "</a></p>";
}
echo " </div></b>
<div id=\"content\" class=\"";
echo $this->contentCssClass;
echo "\"><div class=\"top\"></div>";
$this->printContent();
echo "</div>
<div id=\"side_info\">";

if ($this->player != null) {
    if (1 < sizeof($this->playerVillages)) {
        echo "<table cellpadding=\"1\" cellspacing=\"1\" id=\"vlist\">";
        echo "<thead>";
        echo "<tr>";
        echo "<td colspan=\"3\">";
        echo "<img src=\"assets/x.gif\"";
        echo "class=\"tSwitch dynamic_img opened\"";
        echo "alt=\"\" />&nbsp;<a href=\"village4.php\" accesskey=\"9\">" .
            LANGUI_GAME_LMENU2 .
            ":</a></td>";
        echo "</tr>";
        echo "</thead>";
        echo "<tbody >";
        foreach ($this->playerVillages as $vid => $pvillage) {

            echo "\t\t\t<tr>\r\n\t\t\t\t<td class=\"dot";
            if ($vid == $this->data["selected_village_id"]) {
                echo "  hl";
            }
            echo "\">&bull;</td>";
            echo "<td class=\"link\"><div><a href=\"?vid=";
            echo $vid . $this->villagesLinkPostfix;
            echo "\">";
            echo $pvillage[2];
            echo "</a></div></td>\r\n\t\t\t\t<td class=\"aligned_coords\"><div class=\"cox\">(";
            echo $pvillage[0];
            echo "</div><div class=\"pi\">|</div><div class=\"coy\">";
            echo $pvillage[1];
            echo ")</div> ";
            ?>
            <a href="v2v.php?id=<?php echo $vid .
                $this->villagesLinkPostfix; ?>">
                <img style="margin-left: 2px;" src="assets/default/img/un/h/att_all.gif">
            </a>
            <a href="build.php?bid=17&vid2=<?php echo $vid .
                $this->villagesLinkPostfix; ?>">
                <img src="assets/x.gif" style="margin-left: 2px; background-image: url(assets/default/img/a/report_icons.gif); width: 19px; height: 17px;  background-position: 0 -653px;">
            </a>
            <?php echo "</td>\r\n\t\t\t</tr>\r\n\t\t";
        }
        echo "</tbody></table>";
    }

    if (sizeof($this->playerLinks) && $this->data["active_plus_account"]) {
        echo "<table cellpadding=\"1\" cellspacing=\"1\" id=\"llist\">";
        echo "<thead>";
        echo "<tr>";
        echo "<td colspan=\"3\">";
        echo "<img src=\"assets/x.gif\"";
        echo "class=\"tSwitch dynamic_img opened\"";
        echo "alt=\"\" />&nbsp;<a href=\"profile.php?links\" accesskey=\"9\">" .
            LANGUI_GAME_LMENU3 .
            ":</a></td>";
        echo "</tr>";
        echo "</thead>";
        echo "<tbody >";
        foreach ($this->playerLinks as $link) {
            echo "\t\t\t<tr>\r\n\t\t\t\t<td class=\"dot\">●</td>\r\n\t\t\t\t<td class=\"link\"><div><a href=\"";
            echo htmlspecialchars($link["linkHref"]);
            echo "\"";
            if (!$link["linkSelfTarget"]) {
                echo " target=\"_blank\"";
            }
            echo ">";
            echo $link["linkName"];
            echo "</a>";
            if (!$link["linkSelfTarget"]) {
                echo " <img class=\"external\" src=\"assets/x.gif\" alt=\"";
                echo LANGUI_GAME_LMENU4;
                echo "\" title=\"";
                echo LANGUI_GAME_LMENU4;
                echo "\">";
            }
            echo "</div></td>\r\n\t\t\t</tr>\r\n\t\t\t";
        }
        echo "\t\t</tbody>\r\n\t</table>\r\n\t";
    }
}

if ($this->player != null) {
    echo " <div align=\"center\" style=\"position: absolute; left: ";
    echo $this->appConfig["system"]["lang"] == "en" ? "1000" : "-850";
    echo "px; top: 35px;\">";

    echo "</div>";
}
echo " </div>";

if ($this->player != null) { ?>

<div id="res" >
    <div class="flex-container" style="margin-left: 100px;">
        <div class="flex-item">
            <img src="assets/x.gif" class="r1" title="<?php echo item_title_1; ?>" />
            <div id="l4" title="<?php echo $this->resources[1][
                "calc_prod_rate"
            ]; ?>">
                <?php echo $this->resources[1]["current_value"]; ?>
                <span style="display: none;"><?php echo "/" .
                    $this->resources[1]["store_max_limit"]; ?></span>
            </div>
        </div>

        <div class="flex-item">
            <img src="assets/x.gif" class="r2" title="<?php echo item_title_2; ?>" />
            <div id="l3"  title="<?php echo $this->resources[2][
                "calc_prod_rate"
            ]; ?>">
                <?php echo $this->resources[2]["current_value"]; ?>
                <span style="display: none;"><?php echo "/" .
                    $this->resources[2]["store_max_limit"]; ?></span>
            </div>
        </div>

        <div class="flex-item">
            <img src="assets/x.gif" class="r3" title="<?php echo item_title_3; ?>" />
            <div id="l2"  title="<?php echo $this->resources[3][
                "calc_prod_rate"
            ]; ?>">
                <?php echo $this->resources[3]["current_value"]; ?>
                <span style="display: none;"><?php echo "/" .
                    $this->resources[3]["store_max_limit"]; ?></span>
            </div>
        </div>

        <div class="flex-item">
            <img src="assets/x.gif" class="r4" title="<?php echo item_title_4; ?>" />
            <div id="l1" title="<?php echo $this->resources[4][
                "calc_prod_rate"
            ]; ?>">
                <?php echo $this->resources[4]["current_value"]; ?>
                <span style="display: none;"><?php echo "/" .
                    $this->resources[4]["store_max_limit"]; ?></span>
            </div>
        </div>
    </div>
</div>


</div>
</div>
<?php }
?>


<div class="open-menu" onclick="toggleMobileMenu()">
  <img src="https://cdn-icons-png.flaticon.com/512/6711/6711395.png" alt="open" width="100%">
</div>

<ht class="mobile-menu" style="display: none">
  <div class="close-menu" onclick="toggleMobileMenu()">
    <img src="https://static.vecteezy.com/system/resources/thumbnails/018/886/521/small_2x/signs-close-icon-png.png" alt="close" width="100%">
  </div>
  <a href="index.php">الصفحة الرئيسية</a>
  <a href="profile.php">بطاقة العضوية</a>
  <a href="logout.php">تسجيل الخروج</a>
  <br>
  <a href="farm.php">قائمة <b>
      <font color="#71D000">المزارع</font>
      <font color="#FF6F0F"></font>
      <font color="#71D000"></font>
      <font color="#FF6F0F"></font>
    </b>
  </a>
  <a href="chat.php">الشات</a>
  <a href="msg.php?uid=1"> الدعم </a>
  <hr>
  <?php if ($this->player != null) {
      if (1 < sizeof($this->playerVillages)) {
          echo "<table cellpadding=\"1\" cellspacing=\"1\" id=\"vlist\">";
          echo "<thead>";
          echo "<tr>";
          echo "<td colspan=\"3\">";
          echo "<a href=\"village4.php\" accesskey=\"9\">" .
              LANGUI_GAME_LMENU2 .
              ":</a></td>";
          echo "</tr>";
          echo "</thead>";
          echo "<tbody >";
          foreach ($this->playerVillages as $vid => $pvillage) {

              echo "<td style='padding-right: 10px;' class=\"link\"><div><a href=\"?vid=";
              echo $vid . $this->villagesLinkPostfix;
              echo "\">";
              echo $pvillage[2];
              echo "</a></div ></td>\r\n\t\t\t\t<td class=\"aligned_coords\"><div class=\"cox\">(";
              echo $pvillage[0];
              echo "</div><div class=\"pi\">|</div><div class=\"coy\">";
              echo $pvillage[1];
              echo ")</div> ";
              ?>
            <a href="v2v.php?id=<?php echo $vid .
                $this->villagesLinkPostfix; ?>">
                <img style="margin-left: 2px;" src="assets/default/img/un/h/att_all.gif">
            </a>
            <a href="build.php?bid=17&vid2=<?php echo $vid .
                $this->villagesLinkPostfix; ?>">
                <img src="assets/x.gif" style="margin-left: 2px; background-image: url(assets/default/img/a/report_icons.gif); width: 19px; height: 17px;  background-position: 0 -653px;">
            </a>
            <?php echo "</td>\r\n\t\t\t</tr>\r\n\t\t";
          }
          echo "</tbody></table>";
      }

      if (sizeof($this->playerLinks) && $this->data["active_plus_account"]) {
          echo "<table cellpadding=\"1\" cellspacing=\"1\" id=\"llist\">";
          echo "<thead>";
          echo "<tr>";
          echo "<td colspan=\"3\">";
          echo "<img src=\"assets/x.gif\"";
          echo "class=\"tSwitch dynamic_img opened\"";
          echo "alt=\"\" />&nbsp;<a href=\"profile.php?links\" accesskey=\"9\">" .
              LANGUI_GAME_LMENU3 .
              ":</a></td>";
          echo "</tr>";
          echo "</thead>";
          echo "<tbody >";
          foreach ($this->playerLinks as $link) {
              echo "\t\t\t<tr>\r\n\t\t\t\t<td class=\"dot\">●</td>\r\n\t\t\t\t<td class=\"link\"><div><a href=\"";
              echo htmlspecialchars($link["linkHref"]);
              echo "\"";
              if (!$link["linkSelfTarget"]) {
                  echo " target=\"_blank\"";
              }
              echo ">";
              echo $link["linkName"];
              echo "</a>";
              if (!$link["linkSelfTarget"]) {
                  echo " <img class=\"external\" src=\"assets/x.gif\" alt=\"";
                  echo LANGUI_GAME_LMENU4;
                  echo "\" title=\"";
                  echo LANGUI_GAME_LMENU4;
                  echo "\">";
              }
              echo "</div></td>\r\n\t\t\t</tr>\r\n\t\t\t";
          }
          echo "\t\t</tbody>\r\n\t</table>\r\n\t";
      }
  } ?>
</ht>

<script>
function toggleMobileMenu(){
    document.querySelector('.mobile-menu').classList.toggle("show-flex");
}

</script>

<script type="text/javascript">
init();
</script>


</body>
