<?php


echo "<div id=\"textmenu\">\r\n   <a href=\"build.php?id=";
echo $this->buildingIndex; 
echo "\"";
if ( $this->selectedTabIndex == 0 )
{
    echo " class=\"selected\"";
}
echo ">";
echo LANGUI_CUSTBU_HRO_p1;
echo "</a>\r\n | <a href=\"build.php?id=";
echo $this->buildingIndex;
echo "&t=1\"";
if ( $this->selectedTabIndex == 1 )
{
    echo " class=\"selected\"";
}
echo ">";
echo LANGUI_CUSTBU_HRO_p2;
echo "</a>\r\n | <a href=\"build.php?id=";
echo $this->buildingIndex;
echo "&hero=rename\"";
echo ">";
echo "تغيير اسم البطل";
echo "</a>\r\n</div>\r\n";





if ( $this->selectedTabIndex == 0 )
{
require( APP_PATH."config.php" );
$link = mysql_connect($AppConfig['db']['host'],$AppConfig['db']['user'],$AppConfig['db']['password']) or die(mysql_error());
mysql_select_db($AppConfig['db']['database'],$link) or die(mysql_error());
$Id = $this->player->playerId;
$result = mysql_query("SELECT * FROM p_players where id='".$Id."'");
$r = mysql_fetch_array($result);
if ($r['hero_in_village_id'] == '999999999999999') {
echo "لايوجد بطل";
}else 
    if ( !$this->hasHero )
    {
        if ( !isset( $this->queueModel->tasksInQueue[$this->troopsUpgradeType] ) )
        {
            echo "<table class=\"build_details\" cellpadding=\"1\" cellspacing=\"1\">\r\n\t<thead>\r\n\t\t<tr>\r\n\t\t\t<td colspan=\"2\">";
            echo LANGUI_CUSTBU_HRO_p1_t1;
            echo "</td>\r\n\t\t</tr>\r\n\t</thead>\r\n\t<tbody>\r\n\t\t";
            $_c = 0;
            foreach ( $this->troops as $tid => $tnum )
            {
                if ( $tnum <= 0 )
                {
                    continue;
                }
                ++$_c;
                $troopMetadata = $this->gameMetadata['troops'][$tid];
                $lvlTime = intval( $troopMetadata['training_time_consume'] / $this->gameSpeed * ( 10 / ( $this->buildProperties['building']['level'] + 9 ) ) ) * 12;
                $res = array(
                    "1" => $troopMetadata['training_resources'][1] * 2,
                    "2" => $troopMetadata['training_resources'][2] * 2,
                    "3" => $troopMetadata['training_resources'][3] * 2,
                    "4" => $troopMetadata['training_resources'][4] * 2
                );
                echo "\t\t<tr>\r\n\t\t\t<td class=\"desc\">\r\n\t\t\t\t<div class=\"tit\">\r\n\t\t\t\t\t<img class=\"unit u";
                echo $tid;
                echo "\" src=\"assets/x.gif\" alt=\"";
                echo constant( "troop_".$tid );
                echo "\" title=\"";
                echo constant( "troop_".$tid );
                echo "\"> <a href=\"#\" onclick=\"return showManual(3,";
                echo $tid;
                echo ");\">";
                echo constant( "troop_".$tid );
                echo "</a>\r\n\t\t\t\t</div>\r\n\t\t\t\t<div class=\"details\">\r\n\t\t\t\t\t<img class=\"r1\" src=\"assets/x.gif\" alt=\"";
                echo item_title_1;
                echo "\" title=\"";
                echo item_title_1;
                echo "\">";
                echo "<s";
                echo "pan class=\"little_res\">";
                echo $res[1];
                echo "</span>|<img class=\"r2\" src=\"assets/x.gif\" alt=\"";
                echo item_title_2;
                echo "\" title=\"";
                echo item_title_2;
                echo "\">";
                echo $res[2];
                echo "|<img class=\"r3\" src=\"assets/x.gif\" alt=\"";
                echo item_title_3;
                echo "\" title=\"";
                echo item_title_3;
                echo "\">";
                echo $res[3];
                echo "|<img class=\"r4\" src=\"assets/x.gif\" alt=\"";
                echo item_title_4;
                echo "\" title=\"";
                echo item_title_4;
                echo "\">";
                echo $res[4];
                echo "|<img class=\"clock\" src=\"assets/x.gif\" alt=\"";
                echo text_period_lang;
                echo "\" title=\"";
                echo text_period_lang;
                echo "\">";
                echo WebHelper::secondstostring( $lvlTime );
                echo $this->getResourceGoldExchange( $res, 0, $this->buildingIndex );
                echo "\t\t\t\t</div>\r\n\t\t\t\t";
                echo $this->getActionText2( $res );
                echo "\t\t\t</td>\r\n\t\t\t<td class=\"act\">";
                echo $this->getActionText3( $res, "a=".$tid, LANGUI_CUSTBU_HRO_p1_t7, $this->troopsUpgradeType );
                echo "</td>\r\n\t\t</tr>\r\n\t\t";
            }
            if ( $_c == 0 )
            {
                echo "\t\t<tr><td colspan=\"2\" class=\"none\">";
                echo LANGUI_CUSTBU_HRO_p1_t2;
                echo "</td></tr>\r\n\t\t";
            }
            echo "\t</tbody>\r\n</table>\r\n";
        }
        else
        {
            echo "<p>";
            echo LANGUI_CUSTBU_HRO_p1_t3;
            echo " <b>";
            echo "<s";
            echo "pan id=\"timer1\">";
            echo WebHelper::secondstostring( $this->queueModel->tasksInQueue[$this->troopsUpgradeType][0]['remainingSeconds'] );
            echo "</span></b> ";
            echo time_hour_lang;
        }
    }
    else
    {
require( APP_PATH."config.php" );
$link = mysql_connect($AppConfig['db']['host'],$AppConfig['db']['user'],$AppConfig['db']['password']) or die(mysql_error());
mysql_select_db($AppConfig['db']['database'],$link) or die(mysql_error());
$Id = $this->player->playerId;
$result = mysql_query("SELECT * FROM p_players where id='".$Id."'");
$r = mysql_fetch_array($result);
?>


<table cellspacing="1" cellpadding="1" id="distribution"> 
        <thead>
                <tr>
                        <th colspan="6"><a href="build.php?id=<?php echo $this->buildingIndex; ?>&hero=rename"><?php echo $this->data['hero_name']; ?></a>  المستوى <?php echo $this->data['hero_level']; ?>  <span class="info">( <img title="<?php echo constant( "troop_".$this->data['hero_troop_id'] ); ?>" alt="<?php echo constant( "troop_".$this->data['hero_troop_id'] ); ?>" src="assets/x.gif" class="unit u<?php echo $this->data['hero_troop_id']; ?>"> <?php echo constant( "troop_".$this->data['hero_troop_id'] ); ?>) <?php if ($r['gold_num'] >= 0 and $r['hero_att'] > 0 or $r['hero_deff'] > 0 ) { ?> <a title="اعادة توزيع النقاط" href="build.php?id=<?php echo $this->buildingIndex; ?>&t=2&addgwar"><img title="اعادة توزيع النقاط" class="little_res clock" src="assets/x.gif" alt="Duration"></a> <?php } else { } ?></span></th>
                </tr>
        </thead> 
    <tbody>
        <tr> 
        <th>الهجوم</th> 
        <td class="val"><?php echo $r['hero_att']; ?></td> 
        <td class="xp"><img title="<?php echo $r['hero_att']; ?>" alt="<?php echo $r['hero_att']; ?>" style="width:<?php if ($r['hero_att'] >= 1000) {echo '216'; } else { echo $r['hero_att'] / 5;} ?>px;" src="assets/x.gif" class="bar"></td> 
        <td class="up"><span class="none">
        <?php if ($r['h2ero_points'] >= 9) { ?><a href="build.php?id=<?php echo $this->buildingIndex; ?>&addatt" onClick="this.style.visibility='hidden';">(<b>+</b>)</a><?php }else{ echo '<span class="none">(<b>+</b>)</span>';   } ?>         </span>
                </td>
                        <td class="up"><span class="none">
        <?php if ($r['h2ero_points'] != 0) { ?><a style="color:red;" title="توزيع كل النقاط للهجوم" href="build.php?id=<?php echo $this->buildingIndex; ?>&addattp" onClick="this.style.visibility='hidden';">(<b>+</b>)</a><?php }else{ echo '<span class="none">(<b>+</b>)</span>';   } ?>         </span>
                </td>
    </tr> 
    <tr> 
        <th>الدفاع</th> 
        <td class="val"><?php echo $r['hero_deff']; ?></td> 
        <td class="xp"><img title="<?php echo $r['hero_deff']; ?>%" alt="<?php echo $r['hero_deff']; ?>%" style="width:<?php if ($r['hero_deff'] >= 1000) {echo '216'; } else { echo $r['hero_deff'] / 5;} ?>px;" src="assets/x.gif" class="bar"></td> 
        <td class="up">

                <span class="none">
       <?php if ($r['h2ero_points'] >= 9) { ?><a href="build.php?id=<?php echo $this->buildingIndex; ?>&adddeff" onClick="this.style.visibility='hidden';">(<b>+</b>)</a><?php }else{ echo '<span class="none">(<b>+</b>)</span>';   } ?>         </span>
                </td>
                 <td class="up">

                <span class="none">
       <?php if ($r['h2ero_points'] != 0) { ?><a style="color:red;" title="توزيع كل النقاط للدفاع" href="build.php?id=<?php echo $this->buildingIndex; ?>&adddeffp" onClick="this.style.visibility='hidden';">(<b>+</b>)</a><?php }else{ echo '<span class="none">(<b>+</b>)</span>';   } ?>         </span>
                </td>
    </tr> 
    <tr> 
        <th>مكافئة الهجوم</th> 
        <td class="val"><?php echo $r['hero_att'] / 10; ?>%</td> 
        <td class="xp"><img title="<?php echo $r['hero_att'] / 10; ?>%" alt="<?php echo $r['hero_att'] / 10; ?>%" style="width:<?php if ($r['hero_att'] >= 2160) {echo '216'; } else { echo $r['hero_att'] / 10;} ?>px;" src="assets/x.gif" class="bar"></td> 
        <td class="up"><span class="none"></span></td><td class="up"><span class="none"></span></td>
    </tr> 
    <tr> 
        <th>مكافئة الدفاع</th> 
        <td class="val"><?php echo $r['hero_deff'] / 10; ?>%</td> 
        <td class="xp"><img title="<?php echo $r['hero_deff'] / 10; ?>%" alt="<?php echo $r['hero_deff'] / 10; ?>%" style="width:<?php if ($r['hero_deff'] >= 2160) {echo '216'; } else { echo $r['hero_deff'] / 10;} ?>px;" src="assets/x.gif" class="bar"></td> 
        <td class="up"><span class="none"></span></td><td class="up"><span class="none"></span></td>
    </tr> 
    <tr> 
        <td class="empty" colspan="6"></td>
    </tr> 
    <tr> 
            <th title="خبرة البطل">الخبرة:</th>
        <td class="val"><?php echo $this->data['hero_points']; ?>%</td> 
                <td class="xp"><img title="<?php echo $this->data['hero_points']; ?>%" alt="<?php echo $this->data['hero_points']; ?>%" style="width:<?php if ($r['h2ero_points'] >= 1100) {echo '216'; } else { echo $r['h2ero_points'] / 5;} ?>px;" src="assets/x.gif" class="bar"></td>
        <td class="rem"><?php echo $r['h2ero_points']; ?></td><td class="rem"></td>
        </tr>


    </tbody> 
</table>

<?php
if (isset($_GET['addgwar'])) {
header("Location:build.php?id=".$this->buildingIndex."");
$Id = $this->player->playerId;
$atpo = $r['hero_att'];
$atde = $r['hero_deff'];
mysql_query("UPDATE  `p_players` SET  `gold_num` =gold_num-20 where id='".$Id."'");
mysql_query("UPDATE  `p_players` SET  `hero_att` =0 where id='".$Id."'");
mysql_query("UPDATE  `p_players` SET  `hero_deff` =0 where id='".$Id."'");
mysql_query("UPDATE  `p_players` SET  `h2ero_points` =".$atpo."+".$atde."+h2ero_points where id='".$Id."'");
 }

if (isset($_GET['addatt'])) {
header("Location:build.php?id=".$this->buildingIndex."");
$Id = $this->player->playerId;
if ($r['h2ero_points'] >= 9) {
mysql_query("UPDATE  `p_players` SET  `hero_att` =hero_att+10 where id='".$Id."'");
mysql_query("UPDATE  `p_players` SET  `h2ero_points` =h2ero_points-10 where id='".$Id."'");
}
}

if (isset($_GET['addattp'])) {
header("Location:build.php?id=".$this->buildingIndex."");
$Id = $this->player->playerId;
$rr = $r['h2ero_points']-1;
if ($r['h2ero_points'] >= $rr) {
mysql_query("UPDATE  `p_players` SET  `hero_att` =hero_att+h2ero_points where id='".$Id."'");
mysql_query("UPDATE  `p_players` SET  `h2ero_points` =h2ero_points-h2ero_points where id='".$Id."'");
}
}

if (isset($_GET['adddeff'])) {
if ($r['h2ero_points'] >= 9) {
header("Location:build.php?id=".$this->buildingIndex."");
mysql_query("UPDATE  `p_players` SET  `hero_deff` =hero_deff+10 where id='".$Id."'");
mysql_query("UPDATE  `p_players` SET  `h2ero_points` =h2ero_points-10 where id='".$Id."'");
}
}

if (isset($_GET['adddeffp'])) {
$r1 = $r['h2ero_points']-1;
if ($r['h2ero_points'] >= $r1) {
header("Location:build.php?id=".$this->buildingIndex."");
mysql_query("UPDATE  `p_players` SET  `hero_deff` =hero_deff+h2ero_points where id='".$Id."'");
mysql_query("UPDATE  `p_players` SET  `h2ero_points` =h2ero_points-h2ero_points where id='".$Id."'");
}
}
if ($_GET['hero'] == 'rename') {
echo "<p>";
        echo "<form method=\"post\" name=\"snd\" action=\"build.php?id=";
        echo $this->buildingIndex;
        echo "\">\r\n<table id=\"distribution\" cellpadding=\"1\" cellspacing=\"1\"><tbody>\r\n\t\t\r\n\t\t<tr>\r\n\t\t\t<th>";
        echo LANGUI_CUSTBU_HRO_p1_t5;
        echo ":</th>\r\n\t\t\t<td class=\"val\"><input tabindex=\"6\" type=\"text\" name=\"hname\" value=\"";
        echo htmlspecialchars( $this->data['hero_name'] );
        echo "\" maxlength=\"20\" class=\"text\"></td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n<p class=\"btn\"><input type=\"image\" value=\"\" tabindex=\"9\" name=\"s1\" id=\"btn_save\" class=\"dynamic_img\" src=\"assets/x.gif\" alt=\"";
        echo LANGUI_CUSTBU_HRO_p1_t6;
        echo "\"></p>\r\n</form>\r\n";
}

    }
}
else if ( $this->selectedTabIndex == 1 )
{
    
    echo "العدد الأقصى للواحات التي يمكنك امتلاكها هو <b> 3 </b> واحات";
    echo "<br>";
    echo "تأثير الواحات يكون على <b style='color:green;'> جميع القرى </b> التي تمتلكها ، بمجرد إحتلالك لواحة، يتم إضافتها تلقائيا لجميع القرى. ";
    echo "<br><br>";
    echo "<table id=\"oases\" cellpadding=\"1\" cellspacing=\"1\">\r\n\t<thead>\r\n\t\t<tr><th colspan=\"5\">";
    echo LANGUI_CUSTBU_HRO_p2_t1;
    echo "</th></tr>\r\n\t\t<tr>\r\n\t\t\t<td> </td>\r\n\t\t\t<td>";
    echo LANGUI_CUSTBU_HRO_p2_t2;
    echo "</td>\r\n\t\t\t<td>";
    echo LANGUI_CUSTBU_HRO_p2_t3;
    echo "</td>\r\n\t\t\t<td>";
    echo LANGUI_CUSTBU_HRO_p2_t4;
    echo "</td>\r\n\t\t\t<td>";
    echo LANGUI_CUSTBU_HRO_p2_t5;
    echo "</td>\r\n\t\t</tr>\r\n\t</thead>\r\n\t<tbody>\r\n\t\t";
    foreach ( $this->villageOases as $oasis )
    {
        echo "\t\t<tr>\r\n\t\t\t<td>\r\n\t\t\t\t";
        if ( !isset( $this->queueModel->tasksInQueue[QS_LEAVEOASIS][$oasis['id']] ) )
        {
            echo "\t\t\t\t<a href=\"build.php?id=";
            echo $this->buildingIndex;
            echo "&t=1&a=";
            echo $oasis['id'];
            echo "&k=";
            echo $this->data['update_key'];
            echo "\"><img class=\"del\" src=\"assets/x.gif\" alt=\"";
            echo LANGUI_CUSTBU_HRO_p2_t6;
            echo "\" title=\"";
            echo LANGUI_CUSTBU_HRO_p2_t6;
            echo "\"></a>\r\n\t\t\t\t";
        }
        echo "\t\t\t</td>\r\n\t\t\t<td class=\"nam\"><a href=\"village3.php?id=";
        echo $oasis['id'];
        echo "\">";
        echo LANGUI_CUSTBU_HRO_p2_t7;
        echo "</a></td>\r\n\t\t\t<td class=\"aligned_coords\"><div class=\"cox\">(";
        echo $oasis['rel_x'];
        echo "</div><div class=\"pi\">|</div><div class=\"coy\">";
        echo $oasis['rel_y'];
        echo ")</div></td>\r\n\t\t\t<td class=\"zp\">";
        echo $oasis['allegiance_percent'];
        echo "%</td>\r\n\t\t\t<td class=\"res\">\r\n";
        $oid = $this->setupMetadata['oasis'][$oasis['image_num']];
        $str = "";
        foreach ( $oid as $k => $v )
        {
            if ( $str != "" )
            {
                $str .= PHP_EOL." ".text_and_lang." ";
            }
            $str .= sprintf( "<img class=\"r%s\" src=\"assets/x.gif\" alt=\"%s\" title=\"%s\">+%s%%", $k, constant( "item_title_".$k ), constant( "item_title_".$k ), $v );
        }
        echo $str;
        echo "</td>\r\n\t\t</tr>\r\n\t\t";
    }
    echo "\t</tbody>\r\n</table><br/><br/>\r\n\r\n";
    if ( isset( $this->queueModel->tasksInQueue[QS_LEAVEOASIS] ) )
    {
        echo "<h2>";
        echo LANGUI_CUSTBU_HRO_p2_t6;
        echo "</h2>\r\n<table id=\"leave\" cellpadding=\"1\" cellspacing=\"1\">\r\n\t<thead>\r\n\t\t<tr>\r\n\t\t\t<td>";
        echo LANGUI_CUSTBU_HRO_p2_t2;
        echo "</td>\r\n\t\t\t<td>";
        echo LANGUI_CUSTBU_HRO_p2_t3;
        echo "</td>\r\n\t\t\t<td>";
        echo text_period_lang;
        echo "</td>\r\n\t\t</tr>\r\n\t</thead>\r\n\t<tbody>\r\n\t\t";
        foreach ( $this->queueModel->tasksInQueue[QS_LEAVEOASIS] as $oasisId => $qtArray )
        {
            $qt = $qtArray[0];
            $coordArray = explode( " ", $qt['proc_params'] );
            echo "\t\t<tr>\r\n\t\t\t<td class=\"nam\">\r\n\t\t\t\t<a href=\"build.php?id=";
            echo $this->buildingIndex;
            echo "&t=1&qid=";
            echo $qt['id'];
            echo "\"><img class=\"del\" src=\"assets/x.gif\" alt=\"";
            echo LANGUI_CUSTBU_HRO_p2_t8;
            echo "\" title=\"";
            echo LANGUI_CUSTBU_HRO_p2_t8;
            echo "\"></a>\r\n\t\t\t\t<a href=\"village3.php?id=";
            echo $oasisId;
            echo "\">";
            echo LANGUI_CUSTBU_HRO_p2_t7;
            echo "</a>\r\n\t\t\t</td>\r\n\t\t\t<td class=\"aligned_coords\"><div class=\"cox\">(";
            echo $coordArray[0];
            echo "</div><div class=\"pi\">|</div><div class=\"coy\">";
            echo $coordArray[1];
            echo ")</div></td>\r\n\t\t\t<td class=\"dur\">";
            echo "<s";
            echo "pan id=\"timer1\">";
            echo WebHelper::secondstostring( $qt['remainingSeconds'] );
            echo "</span></td>\r\n\t\t</tr>\r\n\t\t";
        }
        echo "\t</tbody>\r\n</table>\r\n";
    }
    echo "<br/>\r\n";
}
?>